[Feature] Add Inhuman Stats to the roll
TheLastScrub/delta-green-foundry-vtt-system-unofficial pull request #29
Opened 2021-03-08 00:40 UTC by uriele

I had support to the inhuman stat test [pag 188 of the Handler guide], now if a stat is 20+, you will roll against the value instead of the x5.

Every results besides 100 is a success, on top of matching dice, every result below the stat value is a critical.

Works also with modifiers (note however that the modifiers applies  to the stat value and not to the x5 value). 

Note: I assumed that if you modify a stat that is at 20, by reducing it, the stat it still inhuman.

Good job with the module, let me know if I can help with other functions

Marco

2021-03-13 05:17 UTC, TheLastScrub commented
Thanks, might need a little time to review but this is interesting.  Never thought to try to add any mechanics from the handler's guide.

2021-03-13 05:32 UTC, uriele commented
That and the ritual skill (99-current SAN) are the only rules in the Handler guide to be honest. But usually inhuman stats comes up more often :)

2021-03-14 04:39 UTC, TheLastScrub requested changes
system.json needs to match current file before merging (I'll change this part when building the new package).

2021-03-14 04:57 UTC, TheLastScrub approved these changes

2021-03-14 06:06 UTC, merged